Refactor GitHub Actions workflow to rename job from 'release' to 'publish' and streamline Helm chart packaging process

diff --git a/.github/workflows/publish-helm-charts.yml b/.github/workflows/publish-helm-charts.yml
--- a/.github/workflows/publish-helm-charts.yml
+++ b/.github/workflows/publish-helm-charts.yml
@@ -9,20 +9,19 @@ on:
       - main  # Trigger on pull requests to the main branch
 
 jobs:
-  release:
+  publish:
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
+
     steps:
       # Checkout the repository
       - name: Checkout repository
         uses: actions/checkout@v3
 
       # Set up Helm
-      - name: Configure Git
-        run: |
-          git config user.name "$GITHUB_ACTOR"
-          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+      - name: Set up Helm
+        uses: azure/setup-helm@v3
+        with:
+          version: v3.12.0
 
       - name: Update Helm dependencies
         run: |
@@ -33,7 +32,31 @@ jobs:
           done
 
        # Package all charts in the charts/ directory
-      - name: Run chart-releaser
-        uses: helm/chart-releaser-action@v1.7.0
-        env:
-          CR_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
+      - name: Package Helm charts
+        run: |
+          mkdir -p packaged
+          for chart in $(ls -d charts/*/); do
+            if [ -f "$chart/Chart.yaml" ]; then
+              helm package $chart -d packaged
+            else
+              echo "Skipping $chart: Chart.yaml file is missing"
+            fi
+          done
+
+      # Create or update index.yaml
+      - name: Update Helm repository index
+        run: |
+          if git ls-remote --exit-code origin gh-pages; then
+            git fetch origin gh-pages
+            git checkout gh-pages -- index.yaml || echo "No existing index.yaml found"
+          fi
+          helm repo index packaged --url https://v1flows.github.io/helm-charts --merge index.yaml
+          mv packaged/* .
+
+      # Commit and push to gh-pages branch
+      - name: Deploy to GitHub Pages
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.ACCESS_TOKEN }}
+          publish_dir: ./
+          publish_branch: gh-pages
